server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml      # mybatis配置文件所在路径
  type-aliases-package: com.atguigu.springcloud.entities  # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml     # mapper映射文件

spring:
  application:
    name: microservicecloud-dept                          # 名字 在微服务中很重要
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource          # 当前数据库操作类型
    driver-class-name: com.mysql.jdbc.Driver              # 驱动包
    url: jdbc:mysql://localhost:3306/springcloudDB?characterEncoding=utf8&serverTimezone=GMT%2b8&useSSL=false&allowMultiQueries=true
    username: root
    password: chen
    dbcp2:
      min-idle: 5                                          # 最小连接数
      initial-size: 5                                      # 初始化连接数
      max-total: 5                                         # 最大连接数
