server:
  port: 80

eureka:
  client:
    service-url:
      #单机
      #defaultZone: http://localhost:7001/eureka  # 服务端地址
      #集群
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: false